export type ToolCategory =
  | 'Compress'
  | 'Convert'
  | 'AI PDF'
  | 'Organize'
  | 'View & Edit'
  | 'Convert from PDF'
  | 'Convert to PDF'
  | 'Sign'
  | 'More'
  | 'Scan';

export interface PDFTool {
  name: string;
  slug: string;
  category: ToolCategory;
  description: string;
  icon?: string;
  pageTitle: string;
  pageDescription: string;
  metaTitle: string;
  metaDescription: string;
  acceptTypes: Record<string, string[]>;
  multiFile: boolean;
  processLabel: string;
  downloadLabel: string;
  color: string;
  implemented: boolean;
}

export const toolsConfig: PDFTool[] = [
  // ── Compress ──
  {
    name: 'Compress PDF',
    slug: 'compress-pdf',
    category: 'Compress',
    description: 'Reduce the size of your PDF online for free.',
    pageTitle: 'Compress PDF Files',
    pageDescription: 'Optimize your PDF file size locally in your browser.',
    metaTitle: 'Compress PDF Files Online for Free',
    metaDescription: 'Reduce the file size of your PDF documents while retaining the best quality. Easy, fast, and secure.',
    acceptTypes: { 'application/pdf': ['.pdf'] },
    multiFile: false,
    processLabel: 'Compress PDF',
    downloadLabel: 'Download Compressed PDF',
    color: 'from-amber-500 to-orange-500',
    implemented: true,
  },

  // ── Convert ──
  {
    name: 'PDF Converter',
    slug: 'pdf-converter',
    category: 'Convert',
    description: 'Convert files to and from PDF online.',
    pageTitle: 'PDF Converter',
    pageDescription: 'Convert files to and from PDF quickly online.',
    metaTitle: 'PDF Converter Online Free - NextoPDF Pro',
    metaDescription: 'Convert files to and from PDF online.',
    acceptTypes: { 'application/pdf': ['.pdf'] },
    multiFile: false,
    processLabel: 'Convert',
    downloadLabel: 'Download',
    color: 'from-blue-500 to-cyan-500',
    implemented: false,
  },

  // ── AI PDF ──
  {
    name: 'AI PDF Assistant',
    slug: 'ai-pdf-assistant',
    category: 'AI PDF',
    description: 'Interact with your PDF using AI.',
    pageTitle: 'AI PDF Assistant',
    pageDescription: 'Interact with your PDF using advanced AI capabilities.',
    metaTitle: 'AI PDF Assistant Online Free - NextoPDF Pro',
    metaDescription: 'Interact with your PDF using AI.',
    acceptTypes: { 'application/pdf': ['.pdf'] },
    multiFile: false,
    processLabel: 'Analyze',
    downloadLabel: 'Download',
    color: 'from-violet-500 to-purple-600',
    implemented: false,
  },
  {
    name: 'Chat with PDF',
    slug: 'chat-with-pdf',
    category: 'AI PDF',
    description: 'Chat with your PDF documents easily.',
    pageTitle: 'Chat with PDF',
    pageDescription: 'Have a conversation with your PDF documents using AI.',
    metaTitle: 'Chat with PDF Online Free - NextoPDF Pro',
    metaDescription: 'Chat with your PDF documents easily.',
    acceptTypes: { 'application/pdf': ['.pdf'] },
    multiFile: false,
    processLabel: 'Start Chat',
    downloadLabel: 'Download',
    color: 'from-violet-500 to-fuchsia-500',
    implemented: false,
  },
  {
    name: 'AI PDF Summarizer',
    slug: 'ai-summarizer',
    category: 'AI PDF',
    description: 'Get quick summaries of your PDF files using AI.',
    pageTitle: 'AI Summarizer',
    pageDescription: 'Analyze and summarize your PDF metadata instantly.',
    metaTitle: 'AI PDF Summarizer',
    metaDescription: 'Get an AI-generated summary of your PDF content locally.',
    acceptTypes: { 'application/pdf': ['.pdf'] },
    multiFile: false,
    processLabel: 'Analyze PDF',
    downloadLabel: 'Download Summary',
    color: 'from-indigo-500 to-violet-600',
    implemented: true,
  },
  {
    name: 'Translate PDF',
    slug: 'translate-pdf',
    category: 'AI PDF',
    description: 'Translate PDF text into different languages.',
    pageTitle: 'Translate PDF',
    pageDescription: 'Translate the text content of your PDF into another language.',
    metaTitle: 'Translate PDF Online Free - NextoPDF Pro',
    metaDescription: 'Translate PDF text into different languages instantly.',
    acceptTypes: { 'application/pdf': ['.pdf'] },
    multiFile: false,
    processLabel: 'Translate',
    downloadLabel: 'Download Translated PDF',
    color: 'from-sky-500 to-blue-600',
    implemented: true,
  },
  {
    name: 'AI Question Generator',
    slug: 'ai-question-generator',
    category: 'AI PDF',
    description: 'Generate questions automatically from your PDF content.',
    pageTitle: 'AI Question Generator',
    pageDescription: 'Auto-generate study questions from your PDF.',
    metaTitle: 'AI Question Generator Online Free - NextoPDF Pro',
    metaDescription: 'Generate questions automatically from your PDF content.',
    acceptTypes: { 'application/pdf': ['.pdf'] },
    multiFile: false,
    processLabel: 'Generate Questions',
    downloadLabel: 'Download',
    color: 'from-emerald-500 to-teal-600',
    implemented: false,
  },

  // ── Organize ──
  {
    name: 'Merge PDF',
    slug: 'merge-pdf',
    category: 'Organize',
    description: 'Combine multiple PDFs into one document.',
    pageTitle: 'Merge PDF Files',
    pageDescription: 'Combine multiple PDFs into a single document in seconds.',
    metaTitle: 'Merge PDF Files Online for Free',
    metaDescription: 'Combine multiple PDF files into one single document securely in your browser. No installation required.',
    acceptTypes: { 'application/pdf': ['.pdf'] },
    multiFile: true,
    processLabel: 'Merge PDFs',
    downloadLabel: 'Download Merged PDF',
    color: 'from-blue-500 to-blue-600',
    implemented: true,
  },
  {
    name: 'Split PDF',
    slug: 'split-pdf',
    category: 'Organize',
    description: 'Separate one page or a whole set for easy conversion into independent PDF files.',
    pageTitle: 'Split PDF Files',
    pageDescription: 'Extract pages or separate a PDF document into multiple files.',
    metaTitle: 'Split PDF Files Online for Free',
    metaDescription: 'Extract specific pages or page ranges from your PDF document easily and securely in your browser.',
    acceptTypes: { 'application/pdf': ['.pdf'] },
    multiFile: false,
    processLabel: 'Split PDF',
    downloadLabel: 'Download Split PDF',
    color: 'from-emerald-500 to-emerald-600',
    implemented: true,
  },
  {
    name: 'Rotate PDF',
    slug: 'rotate-pdf',
    category: 'Organize',
    description: 'Rotate your PDFs the way you need them.',
    pageTitle: 'Rotate PDF Pages',
    pageDescription: 'Turn your PDF pages by 90°, 180°, or 270° instantly.',
    metaTitle: 'Rotate PDF Files Online',
    metaDescription: 'Rotate specific pages in your PDF document easily and securely.',
    acceptTypes: { 'application/pdf': ['.pdf'] },
    multiFile: false,
    processLabel: 'Rotate Pages',
    downloadLabel: 'Download Rotated PDF',
    color: 'from-cyan-500 to-teal-500',
    implemented: true,
  },
  {
    name: 'Delete PDF Pages',
    slug: 'delete-pages',
    category: 'Organize',
    description: 'Remove pages from your PDF online.',
    pageTitle: 'Delete PDF Pages',
    pageDescription: 'Remove unwanted pages from your document instantly.',
    metaTitle: 'Delete PDF Pages Online',
    metaDescription: 'Easily select and delete pages from your PDF document for free, without uploading your file to any server.',
    acceptTypes: { 'application/pdf': ['.pdf'] },
    multiFile: false,
    processLabel: 'Delete Selected Pages',
    downloadLabel: 'Download Modified PDF',
    color: 'from-red-500 to-red-600',
    implemented: true,
  },
  {
    name: 'Extract PDF Pages',
    slug: 'extract-pdf-pages',
    category: 'Organize',
    description: 'Get a new document containing only the desired pages.',
    pageTitle: 'Extract PDF Pages',
    pageDescription: 'Select and extract specific pages from your PDF into a new document.',
    metaTitle: 'Extract PDF Pages Online Free',
    metaDescription: 'Extract specific pages from your PDF into a new document. Free, fast, and secure.',
    acceptTypes: { 'application/pdf': ['.pdf'] },
    multiFile: false,
    processLabel: 'Extract Pages',
    downloadLabel: 'Download Extracted PDF',
    color: 'from-teal-500 to-green-500',
    implemented: true,
  },
  {
    name: 'Organize PDF',
    slug: 'organize-pdf',
    category: 'Organize',
    description: 'Sort, add and delete PDF pages.',
    pageTitle: 'Organize PDF',
    pageDescription: 'Reorder, add, and delete pages in your PDF.',
    metaTitle: 'Organize PDF Online Free - NextoPDF Pro',
    metaDescription: 'Sort, add and delete PDF pages with ease.',
    acceptTypes: { 'application/pdf': ['.pdf'] },
    multiFile: false,
    processLabel: 'Save Changes',
    downloadLabel: 'Download PDF',
    color: 'from-indigo-500 to-blue-500',
    implemented: true,
  },

  // ── View & Edit ──
  {
    name: 'Edit PDF',
    slug: 'edit-pdf',
    category: 'View & Edit',
    description: 'Add text, images, shapes or freehand annotations to a PDF document.',
    pageTitle: 'Edit PDF',
    pageDescription: 'Add text and annotations to your PDF document.',
    metaTitle: 'Edit PDF Online Free - NextoPDF Pro',
    metaDescription: 'Add text, images, shapes or freehand annotations to a PDF document.',
    acceptTypes: { 'application/pdf': ['.pdf'] },
    multiFile: false,
    processLabel: 'Save Edits',
    downloadLabel: 'Download Edited PDF',
    color: 'from-orange-500 to-amber-500',
    implemented: true,
  },
  {
    name: 'PDF Annotator',
    slug: 'pdf-annotator',
    category: 'View & Edit',
    description: 'Highlight and annotate your PDF.',
    pageTitle: 'PDF Annotator',
    pageDescription: 'Highlight and annotate your PDF documents.',
    metaTitle: 'PDF Annotator Online Free - NextoPDF Pro',
    metaDescription: 'Highlight and annotate your PDF.',
    acceptTypes: { 'application/pdf': ['.pdf'] },
    multiFile: false,
    processLabel: 'Save Annotations',
    downloadLabel: 'Download',
    color: 'from-yellow-500 to-orange-500',
    implemented: false,
  },
  {
    name: 'PDF Reader',
    slug: 'pdf-reader',
    category: 'View & Edit',
    description: 'View your PDF files online.',
    pageTitle: 'PDF Reader',
    pageDescription: 'View and read your PDF documents online.',
    metaTitle: 'PDF Reader Online Free - NextoPDF Pro',
    metaDescription: 'View your PDF files online.',
    acceptTypes: { 'application/pdf': ['.pdf'] },
    multiFile: false,
    processLabel: 'Open',
    downloadLabel: 'Download',
    color: 'from-gray-500 to-gray-600',
    implemented: true,
  },
  {
    name: 'Number Pages',
    slug: 'number-pages',
    category: 'View & Edit',
    description: 'Add page numbers into PDFs with ease.',
    pageTitle: 'Number Pages',
    pageDescription: 'Add page numbers to your PDF document automatically.',
    metaTitle: 'Number PDF Pages Online Free - NextoPDF Pro',
    metaDescription: 'Add page numbers into PDFs with ease.',
    acceptTypes: { 'application/pdf': ['.pdf'] },
    multiFile: false,
    processLabel: 'Add Numbers',
    downloadLabel: 'Download Numbered PDF',
    color: 'from-slate-500 to-gray-600',
    implemented: true,
  },
  {
    name: 'Crop PDF',
    slug: 'crop-pdf',
    category: 'View & Edit',
    description: 'Crop PDF margins, change PDF page size.',
    pageTitle: 'Crop PDF',
    pageDescription: 'Adjust margins and crop PDF pages.',
    metaTitle: 'Crop PDF Online Free - NextoPDF Pro',
    metaDescription: 'Crop PDF margins, change PDF page size.',
    acceptTypes: { 'application/pdf': ['.pdf'] },
    multiFile: false,
    processLabel: 'Crop PDF',
    downloadLabel: 'Download Cropped PDF',
    color: 'from-lime-500 to-green-500',
    implemented: true,
  },
  {
    name: 'Redact PDF',
    slug: 'redact-pdf',
    category: 'View & Edit',
    description: 'Permanently hide sensitive info in PDFs.',
    pageTitle: 'Redact PDF',
    pageDescription: 'Permanently hide sensitive information in your PDF.',
    metaTitle: 'Redact PDF Online Free - NextoPDF Pro',
    metaDescription: 'Permanently hide sensitive info in PDFs.',
    acceptTypes: { 'application/pdf': ['.pdf'] },
    multiFile: false,
    processLabel: 'Redact',
    downloadLabel: 'Download Redacted PDF',
    color: 'from-red-600 to-rose-600',
    implemented: false,
  },
  {
    name: 'Watermark PDF',
    slug: 'watermark-pdf',
    category: 'View & Edit',
    description: 'Stamp an image or text over your PDF in seconds.',
    pageTitle: 'Watermark PDF',
    pageDescription: 'Add a text or image watermark to every page of your PDF.',
    metaTitle: 'Watermark PDF Online Free - NextoPDF Pro',
    metaDescription: 'Stamp an image or text over your PDF in seconds.',
    acceptTypes: { 'application/pdf': ['.pdf'] },
    multiFile: false,
    processLabel: 'Add Watermark',
    downloadLabel: 'Download Watermarked PDF',
    color: 'from-blue-400 to-indigo-500',
    implemented: true,
  },
  // {
  //   name: 'PDF Form Filler',
  //   slug: 'pdf-form-filler',
  //   category: 'View & Edit',
  //   description: 'Fill out PDF forms quickly and easily.',
  //   pageTitle: 'PDF Form Filler',
  //   pageDescription: 'Fill out PDF forms quickly and easily.',
  //   metaTitle: 'PDF Form Filler Online Free - NextoPDF Pro',
  //   metaDescription: 'Fill out PDF forms quickly and easily.',
  //   acceptTypes: { 'application/pdf': ['.pdf'] },
  //   multiFile: false,
  //   processLabel: 'Fill Form',
  //   downloadLabel: 'Download',
  //   color: 'from-teal-500 to-cyan-500',
  //   implemented: false,
  // },
  // {
  //   name: 'Share PDF',
  //   slug: 'share-pdf',
  //   category: 'View & Edit',
  //   description: 'Share your PDF files seamlessly.',
  //   pageTitle: 'Share PDF',
  //   pageDescription: 'Share your PDF files seamlessly.',
  //   metaTitle: 'Share PDF Online Free - NextoPDF Pro',
  //   metaDescription: 'Share your PDF files seamlessly.',
  //   acceptTypes: { 'application/pdf': ['.pdf'] },
  //   multiFile: false,
  //   processLabel: 'Share',
  //   downloadLabel: 'Download',
  //   color: 'from-green-500 to-emerald-500',
  //   implemented: false,
  // },

  // ── Convert from PDF ──
  {
    name: 'PDF to Word',
    slug: 'pdf-to-word',
    category: 'Convert from PDF',
    description: 'Convert PDF to editable Word documents online for free.',
    pageTitle: 'PDF to Word Converter',
    pageDescription: 'Convert your PDF files into editable Word documents.',
    metaTitle: 'PDF to Word Converter Online Free - NextoPDF Pro',
    metaDescription: 'Convert PDF to editable Word documents online for free.',
    acceptTypes: { 'application/pdf': ['.pdf'] },
    multiFile: false,
    processLabel: 'Convert to Word',
    downloadLabel: 'Download Word File',
    color: 'from-blue-600 to-blue-700',
    implemented: true,
  },
  {
    name: 'PDF to Excel',
    slug: 'pdf-to-excel',
    category: 'Convert from PDF',
    description: 'Extract data from PDF spreadsheets into Excel.',
    pageTitle: 'PDF to Excel Converter',
    pageDescription: 'Extract tables and data from your PDF into Excel format.',
    metaTitle: 'PDF to Excel Converter Online Free - NextoPDF Pro',
    metaDescription: 'Extract data from PDF spreadsheets into Excel.',
    acceptTypes: { 'application/pdf': ['.pdf'] },
    multiFile: false,
    processLabel: 'Convert to Excel',
    downloadLabel: 'Download Excel File',
    color: 'from-green-600 to-green-700',
    implemented: true,
  },
  {
    name: 'PDF to PPT',
    slug: 'pdf-to-ppt',
    category: 'Convert from PDF',
    description: 'Turn your PDF files into easy to edit PPT slideshows.',
    pageTitle: 'PDF to PowerPoint Converter',
    pageDescription: 'Convert PDF pages into PowerPoint presentation slides.',
    metaTitle: 'PDF to PPT Converter Online Free - NextoPDF Pro',
    metaDescription: 'Turn your PDF files into easy to edit PPT slideshows.',
    acceptTypes: { 'application/pdf': ['.pdf'] },
    multiFile: false,
    processLabel: 'Convert to PPT',
    downloadLabel: 'Download PPT File',
    color: 'from-orange-600 to-red-500',
    implemented: true,
  },
  {
    name: 'PDF to JPG',
    slug: 'pdf-to-image',
    category: 'Convert from PDF',
    description: 'Extract images from your PDF or save each page as a separate image.',
    pageTitle: 'PDF to Image Converter',
    pageDescription: 'Transform PDF pages into high-resolution JPG or PNG formats.',
    metaTitle: 'Convert PDF to Images Online',
    metaDescription: 'Easily convert your PDF pages to high-quality JPG or PNG images inside your browser.',
    acceptTypes: { 'application/pdf': ['.pdf'] },
    multiFile: false,
    processLabel: 'Convert to Images',
    downloadLabel: 'Download Images',
    color: 'from-purple-500 to-purple-600',
    implemented: true,
  },

  // ── Convert to PDF ──
  {
    name: 'Word to PDF',
    slug: 'word-to-pdf',
    category: 'Convert to PDF',
    description: 'Make DOC and DOCX files easy to read by converting them to PDF.',
    pageTitle: 'Word to PDF Converter',
    pageDescription: 'Convert your Word documents to PDF format.',
    metaTitle: 'Word to PDF Converter Online Free - NextoPDF Pro',
    metaDescription: 'Make DOC and DOCX files easy to read by converting them to PDF.',
    acceptTypes: { 'application/msword': ['.doc'], 'application/vnd.openxmlformats-officedocument.wordprocessingml.document': ['.docx'] },
    multiFile: false,
    processLabel: 'Convert to PDF',
    downloadLabel: 'Download PDF',
    color: 'from-blue-600 to-indigo-600',
    implemented: true,
  },
  {
    name: 'Excel to PDF',
    slug: 'excel-to-pdf',
    category: 'Convert to PDF',
    description: 'Make EXCEL spreadsheets easy to read by converting them to PDF.',
    pageTitle: 'Excel to PDF Converter',
    pageDescription: 'Convert your Excel spreadsheets to PDF format.',
    metaTitle: 'Excel to PDF Converter Online Free - NextoPDF Pro',
    metaDescription: 'Make EXCEL spreadsheets easy to read by converting them to PDF.',
    acceptTypes: { 'application/vnd.ms-excel': ['.xls'], 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': ['.xlsx'] },
    multiFile: false,
    processLabel: 'Convert to PDF',
    downloadLabel: 'Download PDF',
    color: 'from-green-600 to-teal-600',
    implemented: true,
  },
  {
    name: 'PPT to PDF',
    slug: 'ppt-to-pdf',
    category: 'Convert to PDF',
    description: 'Make PPT and PPTX slideshows easy to view by converting them to PDF.',
    pageTitle: 'PowerPoint to PDF Converter',
    pageDescription: 'Convert your PowerPoint presentations to PDF format.',
    metaTitle: 'PPT to PDF Converter Online Free - NextoPDF Pro',
    metaDescription: 'Make PPT and PPTX slideshows easy to view by converting them to PDF.',
    acceptTypes: { 'application/vnd.ms-powerpoint': ['.ppt'], 'application/vnd.openxmlformats-officedocument.presentationml.presentation': ['.pptx'] },
    multiFile: false,
    processLabel: 'Convert to PDF',
    downloadLabel: 'Download PDF',
    color: 'from-orange-500 to-red-500',
    implemented: true,
  },
  {
    name: 'JPG to PDF',
    slug: 'image-to-pdf',
    category: 'Convert to PDF',
    description: 'Convert JPG images to PDF in seconds.',
    pageTitle: 'Image to PDF',
    pageDescription: 'Transform image files into a cohesive PDF document.',
    metaTitle: 'Images to PDF Converter Online',
    metaDescription: 'Convert multiple images into a combined PDF document locally.',
    acceptTypes: { 'image/png': ['.png'], 'image/jpeg': ['.jpg', '.jpeg'] },
    multiFile: true,
    processLabel: 'Convert to PDF',
    downloadLabel: 'Download PDF',
    color: 'from-pink-500 to-rose-500',
    implemented: true,
  },
  {
    name: 'PDF OCR',
    slug: 'pdf-ocr',
    category: 'Convert to PDF',
    description: 'Make your scanned PDFs searchable.',
    pageTitle: 'PDF OCR',
    pageDescription: 'Make scanned PDFs searchable with OCR technology.',
    metaTitle: 'PDF OCR Online Free - NextoPDF Pro',
    metaDescription: 'Make your scanned PDFs searchable.',
    acceptTypes: { 'application/pdf': ['.pdf'] },
    multiFile: false,
    processLabel: 'Run OCR',
    downloadLabel: 'Download',
    color: 'from-gray-600 to-gray-700',
    implemented: false,
  },

  // ── Sign ──
  {
    name: 'Sign PDF',
    slug: 'sign-pdf',
    category: 'Sign',
    description: 'Sign yourself or request electronic signatures from others.',
    pageTitle: 'Sign PDF',
    pageDescription: 'Add your signature to any PDF document.',
    metaTitle: 'Sign PDF Online Free - NextoPDF Pro',
    metaDescription: 'Sign yourself or request electronic signatures from others.',
    acceptTypes: { 'application/pdf': ['.pdf'] },
    multiFile: false,
    processLabel: 'Sign PDF',
    downloadLabel: 'Download Signed PDF',
    color: 'from-indigo-600 to-purple-600',
    implemented: true,
  },
  {
    name: 'Request Signatures',
    slug: 'request-signatures',
    category: 'Sign',
    description: 'Send PDFs out for electronic signature.',
    pageTitle: 'Request Signatures',
    pageDescription: 'Send PDFs for electronic signatures.',
    metaTitle: 'Request Signatures Online Free - NextoPDF Pro',
    metaDescription: 'Send PDFs out for electronic signature.',
    acceptTypes: { 'application/pdf': ['.pdf'] },
    multiFile: false,
    processLabel: 'Send',
    downloadLabel: 'Download',
    color: 'from-purple-500 to-pink-500',
    implemented: false,
  },

  // ── More ──
  {
    name: 'Unlock PDF',
    slug: 'unlock-pdf',
    category: 'More',
    description: 'Remove PDF password security.',
    pageTitle: 'Unlock PDF',
    pageDescription: 'Remove password protection from your PDF files.',
    metaTitle: 'Unlock PDF Online Free - NextoPDF Pro',
    metaDescription: 'Remove PDF password security easily.',
    acceptTypes: { 'application/pdf': ['.pdf'] },
    multiFile: false,
    processLabel: 'Unlock PDF',
    downloadLabel: 'Download Unlocked PDF',
    color: 'from-yellow-500 to-amber-600',
    implemented: true,
  },
  {
    name: 'Protect PDF',
    slug: 'protect-pdf',
    category: 'More',
    description: 'Encrypt your PDF with a password.',
    pageTitle: 'Protect PDF',
    pageDescription: 'Add password protection to your PDF documents.',
    metaTitle: 'Protect PDF Online Free - NextoPDF Pro',
    metaDescription: 'Encrypt your PDF with a password.',
    acceptTypes: { 'application/pdf': ['.pdf'] },
    multiFile: false,
    processLabel: 'Protect PDF',
    downloadLabel: 'Download Protected PDF',
    color: 'from-green-600 to-emerald-600',
    implemented: true,
  },
  {
    name: 'Flatten PDF',
    slug: 'flatten-pdf',
    category: 'More',
    description: 'Make your PDF forms uneditable.',
    pageTitle: 'Flatten PDF',
    pageDescription: 'Flatten interactive forms and annotations in your PDF.',
    metaTitle: 'Flatten PDF Online Free - NextoPDF Pro',
    metaDescription: 'Make your PDF forms uneditable by flattening them.',
    acceptTypes: { 'application/pdf': ['.pdf'] },
    multiFile: false,
    processLabel: 'Flatten PDF',
    downloadLabel: 'Download Flattened PDF',
    color: 'from-slate-500 to-slate-600',
    implemented: true,
  },

  // ── Scan ──
  {
    name: 'PDF Scanner',
    slug: 'pdf-scanner',
    category: 'Scan',
    description: 'Scan physical documents to PDF.',
    pageTitle: 'PDF Scanner',
    pageDescription: 'Scan documents to PDF via your camera.',
    metaTitle: 'PDF Scanner Online Free - NextoPDF Pro',
    metaDescription: 'Scan physical documents to PDF.',
    acceptTypes: { 'image/png': ['.png'], 'image/jpeg': ['.jpg', '.jpeg'] },
    multiFile: true,
    processLabel: 'Create PDF',
    downloadLabel: 'Download PDF',
    color: 'from-cyan-600 to-blue-600',
    implemented: false,
  },
];

export const toolsByCategory = toolsConfig.reduce((acc, tool) => {
  if (!acc[tool.category]) {
    acc[tool.category] = [];
  }
  acc[tool.category].push(tool);
  return acc;
}, {} as Record<ToolCategory, PDFTool[]>);

export const implementedToolsConfig = toolsConfig.filter((tool) => tool.implemented);

export const implementedToolsByCategory = implementedToolsConfig.reduce((acc, tool) => {
  if (!acc[tool.category]) {
    acc[tool.category] = [];
  }
  acc[tool.category].push(tool);
  return acc;
}, {} as Record<ToolCategory, PDFTool[]>);

/** Lookup a tool by its slug */
export function getToolBySlug(slug: string): PDFTool | undefined {
  return toolsConfig.find((t) => t.slug === slug);
}
